/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.hsrw.ci_2_04_programming;

public class App {
    public static void main(String[] args) {
        // Application starting code here
    }
}
