/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.hsrw.ci_2_04_programming.p05_java_software_patterns;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();

        assertNotNull(classUnderTest);
    }
}
